const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT_DIR = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT_DIR, "content", "blog");
const OUTPUT_FILE = path.join(ROOT_DIR, "assets", "data", "blog-posts.json");
const BLOG_OUTPUT_DIR = path.join(ROOT_DIR, "blog");
const SITEMAP_FILE = path.join(ROOT_DIR, "sitemap.xml");
const SCHEDULE_TIME_ZONE = "America/Los_Angeles";
const SITE_URL = "https://taylorthompsonhomegroup.com";
const SITE_NAME = "Taylor Thompson Home Group";
const DEFAULT_AUTHOR = "Taylor Thompson";
const DEFAULT_AUTHOR_URL = `${SITE_URL}/about/`;
const DEFAULT_IMAGE = "/assets/images/hero-1.jpg";
const GENERATED_MARKER = "<!-- Generated by scripts/build-blog.js. Edit the Markdown source in content/blog instead. -->";

const CATEGORIES = {
  "market-updates": "Market Updates",
  "buyer-tips": "Buyer Tips",
  "seller-tips": "Seller Tips",
  "first-time-buyers": "First-Time Buyers",
  investment: "Investment",
  "local-spotlight": "Local Spotlight",
};

const SITEMAP_EXCLUDED_FILES = new Set([
  "404.html",
  "blog-post.html",
  "footer.html",
  "forms.html",
  "idx-wrapper.html",
  "thank-you.html",
]);

const SITEMAP_EXCLUDED_DIRS = new Set([
  ".git",
  "admin",
  "assets",
  "blog",
  "content",
  "includes",
  "node_modules",
  "scripts",
  "tthg",
]);

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function slugify(value) {
  return String(value || "")
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function parseValue(value) {
  const trimmed = value.trim();

  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed === "null") return null;
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
    try {
      return JSON.parse(trimmed.replace(/'/g, '"'));
    } catch (error) {
      return [];
    }
  }

  return trimmed;
}

function parseBlockValue(indicator, blockLines) {
  if (indicator.startsWith(">")) {
    return blockLines
      .join("\n")
      .split(/\n{2,}/)
      .map((paragraph) => paragraph.replace(/\s*\n\s*/g, " ").trim())
      .filter(Boolean)
      .join("\n\n");
  }

  return blockLines.join("\n").trim();
}

function parseFrontmatter(markdown) {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, body: markdown.trim() };

  const data = {};
  const lines = match[1].split(/\r?\n/);
  let currentKey = null;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (!line.trim() || line.trim().startsWith("#")) continue;

    const listItem = line.match(/^\s+-\s+(.*)$/);
    if (listItem && currentKey) {
      if (!Array.isArray(data[currentKey])) data[currentKey] = [];
      data[currentKey].push(parseValue(listItem[1]));
      continue;
    }

    const keyValue = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!keyValue) continue;

    currentKey = keyValue[1];
    const rawValue = keyValue[2];

    if (/^[>|]/.test(rawValue.trim())) {
      const blockLines = [];
      while (index + 1 < lines.length && (!lines[index + 1].trim() || /^\s+/.test(lines[index + 1]))) {
        index += 1;
        blockLines.push(lines[index].trim() ? lines[index].replace(/^\s{2,}/, "") : "");
      }
      data[currentKey] = parseBlockValue(rawValue.trim(), blockLines);
      continue;
    }

    if (rawValue !== "") {
      const valueLines = [rawValue];
      while (
        index + 1 < lines.length &&
        /^\s+/.test(lines[index + 1]) &&
        !/^\s+-\s+/.test(lines[index + 1])
      ) {
        index += 1;
        valueLines.push(lines[index].trim());
      }

      data[currentKey] = parseValue(valueLines.join(" "));
      continue;
    }

    data[currentKey] = [];
  }

  return { data, body: match[2].trim() };
}

function normalizeCategory(value) {
  const slug = slugify(value);
  return CATEGORIES[slug] || String(value || "").trim();
}

function normalizeFeatured(value) {
  if (value === true) return true;
  if (value === false || value === undefined || value === null) return false;
  return ["true", "yes", "1", "featured"].includes(String(value).trim().toLowerCase());
}

function pacificNowParts() {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: SCHEDULE_TIME_ZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    hourCycle: "h23",
  }).formatToParts(new Date());

  return parts.reduce((result, part) => {
    if (part.type !== "literal") result[part.type] = part.value;
    return result;
  }, {});
}

function pacificToday() {
  const now = pacificNowParts();
  return `${now.year}-${now.month}-${now.day}`;
}

function scheduleNumber(date, hour) {
  return Number(`${String(date || "").replace(/-/g, "")}${String(hour || "00:00").slice(0, 2)}`);
}

function currentPacificScheduleNumber() {
  const now = pacificNowParts();
  return scheduleNumber(`${now.year}-${now.month}-${now.day}`, `${now.hour}:00`);
}

function normalizeScheduleHour(value) {
  const match = String(value || "").match(/^(\d{1,2})(?::\d{2})?$/);
  if (!match) return "00:00";

  const hour = Math.max(0, Math.min(23, Number(match[1])));
  return `${String(hour).padStart(2, "0")}:00`;
}

function fileDate(fileName) {
  const match = String(fileName || "").match(/^(\d{4}-\d{2}-\d{2})-/);
  return match ? match[1] : "";
}

function publishDetails(data, fileName) {
  const timing = String(data.publishTiming || data.scheduleTiming || "").toLowerCase();
  const isFuture = timing === "future" || Boolean(data.scheduleDate);
  const date = String((isFuture ? data.scheduleDate : "") || data.date || fileDate(fileName) || pacificToday()).slice(0, 10);
  const hour = normalizeScheduleHour(isFuture ? data.scheduleHour : "00:00");

  return {
    date,
    hour,
    isFuture,
    scheduledAt: `${date} ${hour} PT`,
    scheduleTimezone: SCHEDULE_TIME_ZONE,
    isReady: !isFuture || scheduleNumber(date, hour) <= currentPacificScheduleNumber(),
  };
}

function zonedLocalToIso(date, hour) {
  const dateMatch = String(date || "").match(/^(\d{4})-(\d{2})-(\d{2})$/);
  const hourMatch = String(hour || "00:00").match(/^(\d{2}):(\d{2})$/);
  if (!dateMatch || !hourMatch) return String(date || "");

  const target = Date.UTC(
    Number(dateMatch[1]),
    Number(dateMatch[2]) - 1,
    Number(dateMatch[3]),
    Number(hourMatch[1]),
    Number(hourMatch[2]),
  );
  let instant = new Date(target);

  for (let attempt = 0; attempt < 3; attempt += 1) {
    const parts = new Intl.DateTimeFormat("en-US", {
      timeZone: SCHEDULE_TIME_ZONE,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      hourCycle: "h23",
    }).formatToParts(instant).reduce((result, part) => {
      if (part.type !== "literal") result[part.type] = Number(part.value);
      return result;
    }, {});
    const rendered = Date.UTC(parts.year, parts.month - 1, parts.day, parts.hour, parts.minute);
    instant = new Date(instant.getTime() + (target - rendered));
  }

  return instant.toISOString();
}

function fileUpdatedAt(filePath) {
  try {
    const relativePath = path.relative(ROOT_DIR, filePath).replace(/\\/g, "/");
    const timestamp = execFileSync("git", ["log", "-1", "--format=%ct", "--", relativePath], {
      cwd: ROOT_DIR,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return Number(timestamp) || 0;
  } catch (error) {
    return 0;
  }
}

function escapeHtml(value) {
  return String(value || "").replace(/[&<>"']/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[character]));
}

function escapeJsonForHtml(value) {
  return JSON.stringify(value, null, 2).replace(/</g, "\\u003c");
}

function assetPath(value) {
  const cleanValue = String(value || "").trim();
  if (!cleanValue) return "";
  if (/^(?:https?:)?\/\//i.test(cleanValue) || cleanValue.startsWith("/")) return cleanValue;
  return `/${cleanValue.replace(/^\.?\//, "")}`;
}

function absoluteUrl(value) {
  const cleanValue = assetPath(value);
  if (!cleanValue) return "";
  if (/^https?:\/\//i.test(cleanValue)) return cleanValue;
  if (cleanValue.startsWith("//")) return `https:${cleanValue}`;
  return `${SITE_URL}${cleanValue}`;
}

function plainText(value) {
  return String(value || "")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/<[^>]+>/g, " ")
    .replace(/^[#>*+\-\d.\s]+/gm, "")
    .replace(/[*_`~]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function truncateAtWord(value, maxLength) {
  const text = plainText(value);
  if (text.length <= maxLength) return text;
  const shortened = text.slice(0, maxLength + 1).replace(/\s+\S*$/, "").trim();
  return `${shortened || text.slice(0, maxLength).trim()}...`;
}

function safeLink(value) {
  const href = String(value || "").trim().replace(/^['"]|['"]$/g, "");
  if (!/^(?:https?:\/\/|mailto:|tel:|\/|#)/i.test(href)) return "";
  return href;
}

function linkHtml(label, href) {
  const safeHref = safeLink(href);
  if (!safeHref) return escapeHtml(label);
  const external = /^https?:\/\//i.test(safeHref) && !safeHref.startsWith(SITE_URL);
  const attributes = external ? ' target="_blank" rel="noopener noreferrer"' : "";
  return `<a href="${escapeHtml(safeHref)}"${attributes}>${escapeHtml(label)}</a>`;
}

function renderInlineMarkdown(value) {
  const tokens = [];
  const token = (html) => {
    tokens.push(html);
    return `\u0000TOKEN${tokens.length - 1}\u0000`;
  };

  let text = String(value || "")
    .replace(/<a\s+[^>]*href=(["'])(.*?)\1[^>]*>(.*?)<\/a>/gi, (match, quote, href, label) => (
      token(linkHtml(plainText(label), href))
    ))
    .replace(/\[((?:https?:\/\/)[^\]]+)\]\(<>\)/gi, (match, href) => token(linkHtml(href, href)))
    .replace(/\[([^\]]+)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/g, (match, label, href) => (
      token(linkHtml(label, href))
    ))
    .replace(/<((?:https?:\/\/|mailto:|tel:)[^>\s]+)>/gi, (match, href) => token(linkHtml(href, href)))
    .replace(/(^|[\s(])((?:https?:\/\/)[^\s<>()]+)/gi, (match, prefix, href) => {
      let cleanHref = href;
      let trailing = "";
      while (/[.,!?;:]$/.test(cleanHref)) {
        trailing = `${cleanHref.slice(-1)}${trailing}`;
        cleanHref = cleanHref.slice(0, -1);
      }
      return `${prefix}${token(linkHtml(cleanHref, cleanHref))}${trailing}`;
    });

  text = escapeHtml(text)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/__(.+?)__/g, "<strong>$1</strong>")
    .replace(/(^|[^*])\*([^*]+)\*/g, "$1<em>$2</em>")
    .replace(/(^|[^_])_([^_]+)_/g, "$1<em>$2</em>")
    .replace(/\u0000TOKEN(\d+)\u0000/g, (match, index) => tokens[Number(index)] || "");

  return text;
}

function renderMarkdownImage(line) {
  const match = String(line || "").match(/^!\[([^\]]*)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)$/);
  if (!match) return "";
  const source = assetPath(match[2]);
  if (!source) return "";
  return `<figure class="post-body-image"><img src="${escapeHtml(source)}" alt="${escapeHtml(match[1])}" loading="lazy"></figure>`;
}

function renderMarkdown(markdown) {
  const lines = String(markdown || "").replace(/\r/g, "").split("\n");
  const html = [];
  let listType = "";
  let paragraph = [];
  let quote = [];

  function closeList() {
    if (!listType) return;
    html.push(`</${listType}>`);
    listType = "";
  }

  function flushParagraph() {
    if (!paragraph.length) return;
    html.push(`<p>${renderInlineMarkdown(paragraph.join(" "))}</p>`);
    paragraph = [];
  }

  function flushQuote() {
    if (!quote.length) return;
    html.push(`<blockquote><p>${renderInlineMarkdown(quote.join(" "))}</p></blockquote>`);
    quote = [];
  }

  function flushText() {
    flushParagraph();
    flushQuote();
  }

  lines.forEach((line) => {
    const trimmed = line.trim();

    if (!trimmed) {
      flushText();
      closeList();
      return;
    }

    const heading = trimmed.match(/^(#{1,6})\s+(.+)$/);
    if (heading) {
      flushText();
      closeList();
      const level = Math.min(3, Math.max(2, heading[1].length));
      html.push(`<h${level}>${renderInlineMarkdown(heading[2])}</h${level}>`);
      return;
    }

    if (/^(?:-{3,}|\*{3,}|_{3,})$/.test(trimmed)) {
      flushText();
      closeList();
      html.push("<hr>");
      return;
    }

    const image = renderMarkdownImage(trimmed);
    if (image) {
      flushText();
      closeList();
      html.push(image);
      return;
    }

    if (/^>\s?/.test(trimmed)) {
      flushParagraph();
      closeList();
      quote.push(trimmed.replace(/^>\s?/, ""));
      return;
    }

    const unordered = trimmed.match(/^[-*+\u2022\u2023\u25e6\u2043]\s+(.+)$/);
    if (unordered) {
      flushText();
      if (listType !== "ul") {
        closeList();
        listType = "ul";
        html.push("<ul>");
      }
      html.push(`<li>${renderInlineMarkdown(unordered[1])}</li>`);
      return;
    }

    const ordered = trimmed.match(/^\d+[.)]\s+(.+)$/);
    if (ordered) {
      flushText();
      if (listType !== "ol") {
        closeList();
        listType = "ol";
        html.push("<ol>");
      }
      html.push(`<li>${renderInlineMarkdown(ordered[1])}</li>`);
      return;
    }

    closeList();
    flushQuote();
    paragraph.push(trimmed);
  });

  flushText();
  closeList();
  return html.join("\n");
}

function formatDate(value) {
  const match = String(value || "").match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return String(value || "");
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]))));
}

function readPosts() {
  ensureDir(CONTENT_DIR);

  const posts = fs
    .readdirSync(CONTENT_DIR)
    .filter((file) => file.endsWith(".md"))
    .map((file) => {
      const filePath = path.join(CONTENT_DIR, file);
      const { data, body } = parseFrontmatter(fs.readFileSync(filePath, "utf8"));
      const postBody = body || data.body || data.content || "";

      if (data.published === false) return null;

      const slug = slugify(data.slug || data.title || path.basename(file, ".md"));
      const category = normalizeCategory(data.category);
      const featured = normalizeFeatured(data.featured);
      const publish = publishDetails(data, file);
      const updatedAt = fileUpdatedAt(filePath);
      const datePublished = zonedLocalToIso(publish.date, publish.hour);
      const dateModified = updatedAt ? new Date(updatedAt * 1000).toISOString() : datePublished;

      return {
        id: slug,
        slug,
        url: `/blog/${slug}/`,
        link: `/blog/${slug}/`,
        permalink: `/blog/${slug}/`,
        canonicalUrl: `${SITE_URL}/blog/${slug}/`,
        title: data.title || slug,
        seoTitle: data.seoTitle || "",
        metaDescription: data.metaDescription || "",
        author: data.author || DEFAULT_AUTHOR,
        authorUrl: data.authorUrl || DEFAULT_AUTHOR_URL,
        date: publish.date,
        publishDate: publish.date,
        datePublished,
        dateModified,
        publishTiming: data.publishTiming || (publish.isFuture ? "future" : "now"),
        scheduleDate: publish.date,
        scheduleHour: publish.hour,
        scheduledAt: publish.scheduledAt,
        scheduleTimezone: publish.scheduleTimezone,
        isReady: publish.isReady,
        readTime: data.readTime || "",
        category,
        categories: category ? [category] : [],
        categorySlug: slugify(category),
        excerpt: data.excerpt || "",
        featuredImage: data.featuredImage || "",
        image: data.featuredImage || "",
        imageAlt: data.imageAlt || data.title || "",
        featured,
        isFeatured: featured,
        featuredPost: featured,
        body: postBody,
        content: postBody,
        sourceFile: filePath,
        updatedAt,
      };
    })
    .filter(Boolean)
    .sort((a, b) => new Date(b.datePublished || 0).getTime() - new Date(a.datePublished || 0).getTime());

  const featuredPost = posts
    .filter((post) => post.featured)
    .sort((a, b) => {
      if (b.updatedAt !== a.updatedAt) return b.updatedAt - a.updatedAt;
      return new Date(b.datePublished || 0).getTime() - new Date(a.datePublished || 0).getTime();
    })[0];

  posts.forEach((post) => {
    const isWinner = Boolean(featuredPost && post.slug === featuredPost.slug);
    post.featured = isWinner;
    post.isFeatured = isWinner;
    post.featuredPost = isWinner;
  });

  return posts;
}

function publicPost(post) {
  const { sourceFile, updatedAt, ...publicFields } = post;
  return publicFields;
}

function postPageHtml(post) {
  const canonicalUrl = post.canonicalUrl;
  const title = post.seoTitle || `${post.title} | ${SITE_NAME}`;
  const description = truncateAtWord(post.metaDescription || post.excerpt || post.body, 160);
  const imagePath = assetPath(post.featuredImage || DEFAULT_IMAGE);
  const imageUrl = absoluteUrl(imagePath);
  const bodyHtml = renderMarkdown(post.body);
  const schema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": canonicalUrl,
    },
    headline: post.title,
    description,
    image: [imageUrl],
    datePublished: post.datePublished,
    dateModified: post.dateModified,
    author: {
      "@type": "Person",
      name: post.author,
      url: post.authorUrl,
    },
    publisher: {
      "@type": "Organization",
      name: SITE_NAME,
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        url: `${SITE_URL}/assets/images/favicon.png`,
      },
    },
    articleSection: post.category,
    url: canonicalUrl,
  };

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta name="author" content="${escapeHtml(post.author)}">
  <link rel="canonical" href="${escapeHtml(canonicalUrl)}">
  <link rel="icon" href="/assets/images/favicon.png" type="image/png">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="${SITE_NAME}">
  <meta property="og:title" content="${escapeHtml(post.title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:url" content="${escapeHtml(canonicalUrl)}">
  <meta property="og:image" content="${escapeHtml(imageUrl)}">
  <meta property="og:image:alt" content="${escapeHtml(post.imageAlt)}">
  <meta property="article:published_time" content="${escapeHtml(post.datePublished)}">
  <meta property="article:modified_time" content="${escapeHtml(post.dateModified)}">
  <meta property="article:section" content="${escapeHtml(post.category)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapeHtml(post.title)}">
  <meta name="twitter:description" content="${escapeHtml(description)}">
  <meta name="twitter:image" content="${escapeHtml(imageUrl)}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500&family=Jost:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/assets/css/nav-footer.css">
  <script type="application/ld+json">
${escapeJsonForHtml(schema)}
  </script>
  <style>
    :root{--ink:#050505;--muted:#765f50;--line:#d8cfc7;--paper:#f7f2ed;--white:#fff;--tan:#c8ad9a}
    *{box-sizing:border-box}
    body{margin:0;background:var(--paper);color:var(--ink);font-family:"Jost",Arial,sans-serif;line-height:1.7}
    a{color:inherit;text-decoration-thickness:1px;text-underline-offset:4px}
    .post-shell{width:min(920px,calc(100% - 40px));margin:0 auto;padding:42px 0 72px}
    .back-link{display:inline-flex;align-items:center;gap:8px;margin-bottom:34px;color:var(--muted);font-size:12px;font-weight:700;letter-spacing:.16em;text-decoration:none;text-transform:uppercase}
    .post-hero{background:var(--white);border:1px solid var(--line)}
    .post-image{display:block;width:100%;max-height:520px;object-fit:cover;background:var(--tan)}
    .post-header,.post-content{padding:clamp(28px,5vw,56px)}
    .post-meta{display:flex;flex-wrap:wrap;gap:12px 18px;margin-bottom:18px;color:var(--muted);font-size:12px;font-weight:600;letter-spacing:.18em;text-transform:uppercase}
    h1,h2,h3{margin:0;font-family:"Cormorant Garamond",Georgia,"Times New Roman",serif;font-weight:400;line-height:1.15}
    h1{max-width:760px;font-size:clamp(34px,6vw,62px)}
    .excerpt{max-width:720px;margin:22px 0 0;color:var(--muted);font-size:17px}
    .post-content{border-top:1px solid var(--line);font-size:17px;overflow-wrap:anywhere}
    .post-content h2{margin:38px 0 14px;font-size:clamp(28px,4vw,40px)}
    .post-content h3{margin:30px 0 12px;font-size:clamp(22px,3vw,30px)}
    .post-content p,.post-content ul,.post-content ol,.post-content blockquote,.post-content figure{max-width:100%;margin:0 0 20px}
    .post-content a{position:relative;z-index:1;color:var(--muted);font-weight:600;overflow-wrap:anywhere;text-decoration:underline;word-break:break-word}
    .post-content ul,.post-content ol{padding-left:1.35em}
    .post-content ul{list-style:disc}.post-content ol{list-style:decimal}
    .post-content li{margin:0 0 8px;padding-left:4px}.post-content li::marker{color:var(--tan)}
    .post-content img{display:block;max-width:100%;height:auto}
    .post-content blockquote{border-left:3px solid var(--tan);padding-left:18px;color:var(--muted);font-style:italic}
    .post-content blockquote p{margin:0}
    .post-content hr{height:1px;margin:34px 0;border:0;background:var(--line)}
    .post-content code{padding:.12em .3em;background:var(--paper);font-size:.92em}
    .post-byline{margin-top:34px;padding-top:22px;border-top:1px solid var(--line);color:var(--muted);font-size:14px}
    .post-actions{display:flex;flex-wrap:wrap;gap:14px;justify-content:center;margin-top:28px}
    .post-action{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 24px;background:var(--muted);border:1px solid var(--muted);color:var(--white);font-size:12px;font-weight:700;letter-spacing:.14em;line-height:1;text-decoration:none;text-transform:uppercase}
    .post-action--light{background:var(--white);color:var(--muted)}
    @media(max-width:560px){.post-shell{width:min(100% - 28px,920px);padding-bottom:52px}.post-action{width:100%}.post-header,.post-content{padding:26px 22px}}
  </style>
</head>
<body>
  <div data-include="/includes/header.html"></div>
  <main class="post-shell">
    <a class="back-link" href="/blog">Back to Blogs</a>
    <article class="post-hero">
      ${imagePath ? `<img class="post-image" src="${escapeHtml(imagePath)}" alt="${escapeHtml(post.imageAlt)}" fetchpriority="high">` : ""}
      <header class="post-header">
        <div class="post-meta">
          ${post.category ? `<span>${escapeHtml(post.category)}</span>` : ""}
          <time datetime="${escapeHtml(post.datePublished)}">${escapeHtml(formatDate(post.date))}</time>
          ${post.readTime ? `<span>${escapeHtml(post.readTime)}</span>` : ""}
        </div>
        <h1>${escapeHtml(post.title)}</h1>
        ${post.excerpt ? `<p class="excerpt">${escapeHtml(post.excerpt)}</p>` : ""}
      </header>
      <div class="post-content">
        ${bodyHtml}
        <p class="post-byline">Written by <a href="${escapeHtml(post.authorUrl)}" rel="author">${escapeHtml(post.author)}</a> for ${SITE_NAME}.</p>
      </div>
    </article>
    <nav class="post-actions" aria-label="After blog navigation">
      <a class="post-action post-action--light" href="/blog">Back to Blogs</a>
      <a class="post-action" href="/">Back to Home</a>
    </nav>
  </main>
  <div data-include="/includes/footer.html"></div>
  <script src="/assets/js/includes.js" defer></script>
</body>
</html>
${GENERATED_MARKER}
`;
}

function generatePostPages(posts) {
  if (path.dirname(BLOG_OUTPUT_DIR) !== ROOT_DIR) {
    throw new Error(`Refusing to replace unexpected blog output directory: ${BLOG_OUTPUT_DIR}`);
  }

  fs.rmSync(BLOG_OUTPUT_DIR, { recursive: true, force: true });
  ensureDir(BLOG_OUTPUT_DIR);

  posts.filter((post) => post.isReady).forEach((post) => {
    const outputDir = path.join(BLOG_OUTPUT_DIR, post.slug);
    ensureDir(outputDir);
    fs.writeFileSync(path.join(outputDir, "index.html"), postPageHtml(post));
  });
}

function fileDateString(filePath) {
  try {
    return fs.statSync(filePath).mtime.toISOString().slice(0, 10);
  } catch (error) {
    return pacificToday();
  }
}

function collectSitemapEntries(posts) {
  const entries = new Map();
  const add = (route, lastmod, priority = "0.7") => {
    entries.set(route, { route, lastmod, priority });
  };

  fs.readdirSync(ROOT_DIR, { withFileTypes: true }).forEach((entry) => {
    const fullPath = path.join(ROOT_DIR, entry.name);

    if (entry.isFile() && entry.name.endsWith(".html") && !SITEMAP_EXCLUDED_FILES.has(entry.name)) {
      const route = entry.name === "index.html" ? "/" : `/${path.basename(entry.name, ".html")}`;
      add(route, fileDateString(fullPath), route === "/" ? "1.0" : route === "/blog" ? "0.9" : "0.7");
      return;
    }

    if (!entry.isDirectory() || SITEMAP_EXCLUDED_DIRS.has(entry.name)) return;
    const indexPath = path.join(fullPath, "index.html");
    if (fs.existsSync(indexPath)) add(`/${entry.name}/`, fileDateString(indexPath));
  });

  posts.filter((post) => post.isReady).forEach((post) => {
    add(`/blog/${post.slug}/`, post.dateModified.slice(0, 10), "0.8");
  });

  return Array.from(entries.values()).sort((a, b) => a.route.localeCompare(b.route));
}

function writeSitemap(posts) {
  const entries = collectSitemapEntries(posts);
  const rows = entries.map((entry) => `  <url>
    <loc>${escapeHtml(`${SITE_URL}${entry.route}`)}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <priority>${entry.priority}</priority>
  </url>`).join("\n");
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${rows}
</urlset>
`;
  fs.writeFileSync(SITEMAP_FILE, xml);
}

function buildBlog() {
  ensureDir(path.dirname(OUTPUT_FILE));
  const posts = readPosts();
  const publicPosts = posts.map(publicPost);

  fs.writeFileSync(OUTPUT_FILE, `${JSON.stringify(publicPosts, null, 2)}\n`);
  generatePostPages(posts);
  writeSitemap(posts);

  const readyCount = posts.filter((post) => post.isReady).length;
  console.log(`Built ${posts.length} blog record(s) and ${readyCount} static blog page(s).`);
}

buildBlog();
